### ISSUE TITLE
valid href/location with "?unit=us" fails due to trailing slash that seems to be appended, failing regex match 

### ISSUE THREAD

**Issue by qwickset** [GreenMeteor/humhub-weather-module#9] opened 2020-04-10 02:54 UTC
Widget version: 1.0.3
HumHub version: 1.3.8

It appears that in the message event listener, o.data.href is coming in with an appended "/" which works in nearly all cases but when the unit query string is added to override Celsius to Fahrenheit.  In that case, the browser doesn't load the widget content and the console logs "WeatherWidget.io: Invalid Location format".  

**Steps to reproduce:** 
1. Ensure Weather widget is enabled
2. Enter _https://forecast7.com/en/40d71n74d01/new-york/?unit=us_ into the hum hub weather widget config and hit Save
3. Navigate to the main page

Expected: Weather widget presents New York weather in Farenheit
Actual:  regex evaluates o.data.href of "https://forecast7.com/en/40d71n74d01/new-york/?unit=us/", which fails the regex match which appears to be due to the trailing "/" that got appended along the way.  Weather content is not displayed. Console logs silent error.

**Comment by ArchBlood** [comment] 2020-04-10 18:43
At this time it is recommended to use the Celsius option only, as we have no complete fix for this at the moment, as a reference we'll mark this as a bug to keep it as a known issue.

**Comment by ArchBlood** [comment] 2020-04-10 20:44
The console error `Uncaught ReferenceError: __weatherwidget_init is not defined` can be ignored as this only happens when `__weatherwidget_init()` is referenced which is only once from the widget itself if removed the module will not work as intended to and is only used in `widget.min.js` from the the https://weatherwidget.io/ website, to fix the switch between Celsius to Fahrenheit the simplest way to fix this would be removing the `/` from here;

https://github.com/GreenMeteor/humhub-weather-module/blob/9dd13686851b649cc26fe877d2ed3b2eebe59593/widgets/WeatherFrame.php#L21

If this fixes the issue please reply back so that we can get to work on implementing it and shipping out a new version.

**Comment by qwickset** [comment] 2020-04-10 23:00
That seems to be the step in the right direction although dropping the '/' appendage altogether alienates the use case of not including the query string. I was able to get both cases to work (querystring and not) by making these local updates.  Granted offering FWIW as they may be a bit sloppy due to my limited PHP experience.

**WeatherFrame.php::run()**
        $url = Yii::$app->getModule('weather')->getServerUrl();
	if (strpos($url,'?')==false)
	{
		$url=$url.'/';
	}
        return $this->render('weatherframe', ['weatherUrl' => $url]);


**iApp.min.js**  (can be better written given binary '/' or '?xxxx=yyyy' scenarios)
line 28: var l = r.href.match(/^(https:\/\/forecast7\.com\/)([a-z]{2}(?:-[a-z]{2})?)\/([dn0-9]+\/[-_a-z0-9]+)(\/|\?unit=(us))?$/);

Note: since iApp.min.js is remote, I used a regex expression tester to test the modified regex given he following strings (I didn't have the time at the moment to pull things down locally and change references)

https://forecast7.com/en/40d71n74d01/new-york/
https://forecast7.com/en/40d71n74d01/new-york?unit=us 
https://forecast7.com/en/40d71n74d01/new-york/?unit=us  (for good measure)

since iApp.min.js is remote, I'm unable to resolve the issue temporarily, FWIW.  That said, I submit this research to you for your consideration.

**Comment by qwickset** [comment] 2020-04-10 23:02
To be clear, the proposed issue fixed a configuration of a string that had ?unit=us....but it broke for urls that did not as the existing regex expects a trailing '/' for a match.  Regardless....it is a good start towards a solution to the issue.

**Comment by ArchBlood** [comment] 2020-04-11 02:18
Here place the `/` at the and you should be able to use `https://forecast7.com/en/40d71n74d01/new-york/` or `https://forecast7.com/en/40d71n74d01/new-york/?unit=us` otherwise you'll run into the same issue.

https://github.com/GreenMeteor/humhub-weather-module/blob/9dd13686851b649cc26fe877d2ed3b2eebe59593/Module.php#L29

**Comment by ArchBlood** [comment] 2020-04-11 02:24
Also just to note, using `/?unit=eu` on their site is possible but serves no real purpose as Celsius is used as the default domain listing.

**Closed** 2020-04-11 17:18 UTC
Labels: bug
